import fs from 'node:fs/promises'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '..', '..')
const outputPath = path.resolve(repoRoot, 'typescript/src/generated/python-browser-sources.ts')
const pythonBrowserRoot = path.resolve(repoRoot, 'python_browser')

async function main() {
  const sourceFiles = await collectPythonSourceFiles(pythonBrowserRoot)
  const entries = await Promise.all(
    sourceFiles.map(async (relativePath) => {
      const filePath = path.resolve(repoRoot, relativePath)
      const source = await fs.readFile(filePath, 'utf8')
      return [normalizePythonBundlePath(relativePath), source] as const
    }),
  )

  const contents = `// Auto-generated by scripts/gen-python-browser-sources.ts
export const PYTHON_BROWSER_SOURCES: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, contents, 'utf8')
}

async function collectPythonSourceFiles(rootDir: string): Promise<string[]> {
  const results: string[] = []

  async function walk(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true })
    for (const entry of entries) {
      if (entry.name === '__pycache__') continue
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        await walk(fullPath)
        continue
      }
      if (!entry.isFile() || !entry.name.endsWith('.py')) continue
      results.push(path.relative(repoRoot, fullPath))
    }
  }

  await walk(rootDir)
  results.sort()
  return results
}

function normalizePythonBundlePath(relativePath: string): string {
  if (relativePath.startsWith('python/')) {
    return relativePath.replace(/^python\//, '')
  }
  if (relativePath.startsWith('python_browser/')) {
    return relativePath.replace(/^python_browser\//, '')
  }
  return relativePath
}

void main()
