import {
  AUTHORITY_CONNECT_BODY_HARD_MAX_BYTES,
  AUTHORITY_CONNECT_BODY_LIMIT_BYTES,
  AUTHORITY_HOST_WS_FRAME_LIMIT_BYTES,
  AUTHORITY_PRESENCE_WS_FRAME_LIMIT_BYTES,
} from '../config/constants.js'

export const AUTHORITY_MAX_SERVER_NAME_LENGTH = 255
export const AUTHORITY_MAX_AUTH_TOKEN_LENGTH = 8 * 1024
export const AUTHORITY_MAX_SDP_LENGTH = 48 * 1024
export const AUTHORITY_MAX_REQUEST_ID_LENGTH = 256
export const AUTHORITY_MAX_USER_AGENT_LENGTH = 512
export const AUTHORITY_MAX_IP_LENGTH = 64
export const AUTHORITY_MAX_CLIENT_KEY_LENGTH = 256
export const AUTHORITY_MAX_REASON_LENGTH = 256
export const AUTHORITY_MAX_CONNECTION_ID_LENGTH = 128
export const AUTHORITY_MAX_REGISTRATION_BATCH_SIZE = 128
export const AUTHORITY_MAX_PRESENCE_SUBSCRIPTION_BATCH_SIZE = 256
export const AUTHORITY_MAX_SUPPRESSION_TTL_SECONDS = 24 * 60 * 60

export const AUTHORITY_ALLOWED_SESSION_DESCRIPTION_TYPES = [
  'offer',
  'answer',
  'pranswer',
  'rollback',
] as const

export const AUTHORITY_ALLOWED_AUTH_MODES = [
  'public',
  'private',
  'anonymous',
] as const

export const AUTHORITY_CONNECT_LIMITS = {
  recommendedBodyBytes: AUTHORITY_CONNECT_BODY_LIMIT_BYTES,
  hardBodyBytes: AUTHORITY_CONNECT_BODY_HARD_MAX_BYTES,
  maxServerNameLength: AUTHORITY_MAX_SERVER_NAME_LENGTH,
  maxSdpLength: AUTHORITY_MAX_SDP_LENGTH,
} as const

export const AUTHORITY_WS_LIMITS = {
  hostFrameBytes: AUTHORITY_HOST_WS_FRAME_LIMIT_BYTES,
  presenceFrameBytes: AUTHORITY_PRESENCE_WS_FRAME_LIMIT_BYTES,
  maxTokenLength: AUTHORITY_MAX_AUTH_TOKEN_LENGTH,
  maxRegistrationBatchSize: AUTHORITY_MAX_REGISTRATION_BATCH_SIZE,
  maxPresenceSubscriptionBatchSize: AUTHORITY_MAX_PRESENCE_SUBSCRIPTION_BATCH_SIZE,
} as const

